### PR TITLE
Completed core feature and polished UI

### LINKED ISSUE #28: Core Features Implementation
### 1. ADD
Manual Add: 
>  - [x]  Design UI page for user to manually compose recipe

API Add (use Spoonacular to parse recipe from web) : 
> - [ ]   Add UI for user to parse recipe from a link

General:
>  - [x]  Build a JSON object from input
>  - [x]  Display new recipe card 
>  - [x] Send a message to backend to save JSON file at a directory (Done by backend team)
>  - [x]  Figure out how to inject the cached JSONobject into a web component (also, mapping recipe card the correct JSON file)

 (could be same as ADD page but with the information already populated for each field)
>  - [x] Modify information for the corresponding JSON file 
>  - [x] Modification is reflected on the recipe card on homepage when user hit Save

### LINKED ISSUE #56: Add Import/Export functionality to the frontend
Use the hooks defined in `preload.js` (which make `IOSystem` calls for you) to implement the front end for importing json files and add checkboxes in order to export json files.

Global edit mode (#60) could be considered a soft prerequisite for this.

### PR DESCRIPTION
**Pull request by StefanieDao**
Some changes I made:

- I fixed some bugs with the main features also completed the tag feature. 
- For now, the search can only search for recipe names because I did not have time to do more advanced search. And I haven't had time to do sort yet :'< (I know it's pretty fast but I have other stuff to do, so if u think more advanced search is necessary feel free to implement it)
- I implemented the Favorite function (not perfect since I did not have much time). 
>  - I did not figure out the way to keep the button's color changes permanently after u hit refresh. So the Favorite View is still correct, but the buttons on the cards won't reflect that
> - If you delete a recipe in the Favorite page, u need to hit refresh for the Favorite page to reflect that change. 
- Mainly I fixed a lot of UI stuff so feel free to let me know if it looks okay! 
- @haxoc How is the import/export? Is it done yet? On my end the export does not seem to work. Lmk when u need to merge it into master or sth

### CODE REVIEW

**Comment by haxoc** [comment]
Ok, I changed export to use ID. Now it works

**Comment by haxoc** [comment]
Now this closes #56 and #28

**Review by haxoc — COMMENTED** [review]
I added some changes, so I think someone else should do the approving review.

**Review by jjsinger11 — APPROVED** [review]

**Comment by haxoc** [comment]
@jjsinger11 Did you test import/export

**Comment by StefanieDao** [comment]
Moved to `build-features-ci` branch

**Pull request closed without merging**
